### ISSUE TITLE
ghalint can't parse workflow files that all codes are commented out: `parse a workflow file as YAML: EOF`

### ISSUE THREAD

**Issue by bviswanathan-exelixis** [suzuki-shunsuke/ghalint#197]
@suzuki-shunsuke Not sure how to parse the error, was there an EOF character that results in error -> 

% ghalint run
ERRO[0000] read a workflow file                          error="parse a workflow file as YAML: EOF" program=ghalint version=0.2.2 workflow_file_path=.github/workflows/sample.yaml

**Comment by suzuki-shunsuke** [comment]
Thank you for your report.
Could you tell us workflow files that we can reproduce the issue?

**Comment by bviswanathan-exelixis** [comment]
Thanks @suzuki-shunsuke for prompt response. I have tried with multiple workflows, it gives the same error message. Below is a sample -> 

name: validate

on:
  push:
    branches: ["main"]
  release:
    types: ["published"]

env:
  AWS_REGION: <removed>
  AWS_ACCOUNT_ID: <removed>
  CONTAINER_REGISTRY_NAME: <removed>
  AWS_ROLE_NAME: <removed>
  PATH_TO_DOCKERFILE: docker/dockerfile
  CONTEXT_DIRPATH: ./
  AWS_PROFILE_NAME_TO_GENERATE: <removed>

jobs:
  deploy:
    name: validate
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.AWS_ROLE_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: configure aws cli with credentials
        run: |
          chmod +x ./.github/scripts/generate-aws-credentials
          ./.github/scripts/generate-aws-credentials ${{ env.AWS_PROFILE_NAME_TO_GENERATE }}

      - name: make configs
        run: |
          make configs
        shell: bash

**Comment by suzuki-shunsuke** [comment]
Thank you for sharing.

I copied your workflow file to `.github/workflows/foo.yaml` and run `ghalint run`, but I can't reproduce the issue. 🤔 

```yaml
name: validate

on:
  push:
    branches: ["main"]
  release:
    types: ["published"]

env:
  AWS_REGION: <removed>
  AWS_ACCOUNT_ID: <removed>
  CONTAINER_REGISTRY_NAME: <removed>
  AWS_ROLE_NAME: <removed>
  PATH_TO_DOCKERFILE: docker/dockerfile
  CONTEXT_DIRPATH: ./
  AWS_PROFILE_NAME_TO_GENERATE: <removed>

jobs:
  deploy:
    name: validate
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.AWS_ROLE_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: configure aws cli with credentials
        run: |
          chmod +x ./.github/scripts/generate-aws-credentials
          ./.github/scripts/generate-aws-credentials ${{ env.AWS_PROFILE_NAME_TO_GENERATE }}

      - name: make configs
        run: |
          make configs
        shell: bash
```

```console
$ ghalint -v
ghalint version 0.2.2 (f531012f64f7bcc0b5b0c09a98d2133690b1646b)

$ ghalint run

$ echo $?
0
```
