### ISSUE TITLE
New Rule: Allow List of container images

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/ghalint#207]
```yaml
allowed_container_images:
  - 
```

https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container

```yaml
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: node:18 # Validate
```
