### ISSUE TITLE
New Rule: docker image tag should not be latest

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/ghalint#208]
:x:

```yaml
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: node:latest
```

⭕ 

```yaml
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: node:10 # Ideally, hash is best
```
