### ISSUE TITLE
YAML unmarshall errors with using container

### ISSUE THREAD

**Issue by watarukura** [suzuki-shunsuke/ghalint#235]
#197 is not same error
ghalint v0.2.3

```yaml
---
name: test

on:
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/test.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    container: "composer:2.6.5"
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          sparse-checkout: |
            composer.json
            composer.lock
```

```shell
ERRO[0000] read a workflow file                          error="parse a workflow file as YAML: yaml: unmarshal errors:\n  line 18: cannot unmarshal !!str `compose...` into workflow.Container" program=ghalint version=0.2.3 workflow_file_path=.github/workflows/test.yaml
```

remove jobs.lint.container and success, but it's necessary for me.
v0.2.2 occurs no error.
