### ISSUE TITLE
config.Validate error but quiet

### ISSUE THREAD

**Issue by watarukura** [suzuki-shunsuke/ghalint#240]
My .ghalint.yml was here.

```yaml
---
excludes:
  - policy_name: action_ref_should_be_full_length_commit_sha
    workflow_file_path: .github/workflows/linters.yml
    job_name: markdownlint
```

```shell
bash-5.2$ ghalint run
bash-5.2$ echo $?
1
```

No error message, but `exit 1`.

```yaml
---
excludes:
  - policy_name: action_ref_should_be_full_length_commit_sha
    action_name: torana-us/torana-shared-actions/.github/workflows/wc-markdownlint.yml
```

`action_ref_should_be_full_length_commit_sha` policy need action_name, so I rewrite.
https://github.com/suzuki-shunsuke/ghalint/blob/main/pkg/config/config.go#L49-L51

I want to display error message.
