### ISSUE TITLE
ERRO[0000] job should have permissions

### ISSUE THREAD

**Issue by bviswanathan-exelixis** [suzuki-shunsuke/ghalint#242]
Hello @suzuki-shunsuke, I updated to latest version and now ghalint is giving messages about using SHA for actions in workflow yml. Thank you!. 

Meanwhile, another error message is as below -> 

ERRO[0000] job should have permissions                   job_name=wiz-cli-github-image-scan policy_name=job_permissions program=ghalint version=0.2.5 workflow_file_path=.github/workflows/wiz-cli-github-image-scan.yaml

The error message does not tell what permissions is needed?.

**Comment by bviswanathan-exelixis** [comment]
Another error - 
```
ERRO[0000] read a workflow file                          error="parse a workflow file as YAML: EOF" program=ghalint version=0.2.5 workflow_file_path=.github/workflows/plan.yml

```

**Comment by suzuki-shunsuke** [comment]
> ERRO[0000] job should have permissions job_name=wiz-cli-github-image-scan policy_name=job_permissions program=ghalint version=0.2.5 workflow_file_path=.github/workflows/wiz-cli-github-image-scan.yaml
> The error message does not tell what permissions is needed?.

https://github.com/suzuki-shunsuke/ghalint/blob/main/docs/policies/001.md

The policy means the field `permissions` is missing.

The workflow: .github/workflows/wiz-cli-github-image-scan.yaml
job: wiz-cli-github-image-scan

> ERRO[0000] read a workflow file                          error="parse a workflow file as YAML: EOF" program=ghalint version=0.2.5 workflow_file_path=.github/workflows/plan.yml

Is this duplicate of  https://github.com/suzuki-shunsuke/ghalint/issues/197 ?

**Comment by bviswanathan-exelixis** [comment]
Thanks @suzuki-shunsuke . You are correct, second error seems duplicate of #197 but I copied the wrong error, the error I was going to copy is this one -> 
```
ERRO[0000] secret should not be set to job's env         env_name=TF_VAR_github_token job_name=terraform policy_name=job_secrets program=ghalint version=0.2.5 workflow_file_path=.github/workflows/account_onboard_job.yml
```
The above error is coming because that file has 
```
jobs: 
  terraform:
    name: "onboard-account-job"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./modules/github_account_onboarding
    permissions:
      contents: write
      pull-requests: write
    env:
        TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        
      - name: Terraform Format
        id: fmt
        run: terraform fmt
```
But the token is temporary and only used till job completes. Also this pattern seems to expected as per - https://dev.to/github/the-githubtoken-in-github-actions-how-it-works-change-permissions-customizations-3cgp
