### ISSUE TITLE
Support configuration file

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/ghalint#27]
`^\.?ghalint\.ya?ml$`

* Support exclude policies

```yaml
excludes:
- policy: job_secrets
  workflow_file: .github/workflows/test.yaml
  job: foo
```
