### ISSUE TITLE
Validate container image tag

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/ghalint#282]
- Forbid `latest`
- hash

## Image name and tag format

https://docs.docker.com/engine/reference/commandline/tag/

```
[HOST[:PORT_NUMBER]/]PATH[:TAG]
```

## Docker Hub Action

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-a-docker-hub-action

```yaml
jobs:
  my_first_job:
    steps:
      - name: My first step
        uses: docker://alpine:3.8
```

```
docker://{image}:{tag}
docker://{host}/{image}:{tag}

```

## Docker action

https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#example-using-public-docker-registry-container

```yaml
runs:
  using: 'docker'
  image: 'docker://debian:stretch-slim'
```
