### ISSUE TITLE
Exclusion of github_app_should_limit_repositories for run-action is not working

### ISSUE THREAD

**Issue by itkq** [suzuki-shunsuke/ghalint#471]
I have the following files. 
```yaml
# .github/workflows/ghalint-test.yml
name: 'ghalint-test'

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/create-github-app-token@46e4a501e119d39574a54e53a06c9a705efc55c9 # v1.6.1
        id: app-token
        with:
          app-id: ${{vars.APP_ID}}
          private-key: ${{secrets.PRIVATE_KEY}}
          owner: ${{github.repository_owner}}
```

```yaml
# .github/actions/ghalint-test/action.yml
name: setup-github-app-token
description: Generate Github App token

inputs:
  app_id:
    required: true
    description: The GitHub App ID.
  private_key:
    required: true
    description: The GitHub App private key.
  owner:
    required: true
    description: The owner of enabling the token
outputs:
  token:
    description: The installation token
    value: ${{ steps.app-token.outputs.token }}

runs:
  using: composite
  steps:
    - id: app-token
      uses: actions/create-github-app-token@c8f55efbd427e7465d6da1106e7979bc8aaee856 # v1.10.1
      with:
        app-id: ${{ inputs.app_id }}
        private-key: ${{ inputs.private_key }}
        owner: ${{ inputs.owner }}
```

The workflow and the action violates github_app_should_limit_repositories, so both `ghalint run` and `ghalint run-action` fails.

```
% ghalint --version
ghalint version 0.2.10 (613482225fbdea855ed2a561c7cbd737d7aec7d6)
% ghalint run
ERRO[0000] the step violates policies                    action=actions/create-github-app-token error="action ref should be full length SHA1" job_name=test policy_name=action_ref_should_be_full_length_commit_sha program=ghalint reference="https://github.com/suzuki-shunsuke/ghalint/blob/main/docs/policies/008.md" step_id=app-token version=0.2.10 workflow_file_path=.github/workflows/ghalint-test.yml
% ghalint run-action .github/actions/ghalint-test/action.yml
ERRO[0000] the step violates policies                    action=actions/create-github-app-token action_file_path=.github/actions/ghalint-test/action.yml error="action ref should be full length SHA1" policy_name=action_ref_should_be_full_length_commit_sha program=ghalint reference="https://github.com/suzuki-shunsuke/ghalint/blob/main/docs/policies/008.md" step_id=app-token version=0.2.10
FATA[0000] ghalint failed
```

After that, I created the following config (ref. https://github.com/suzuki-shunsuke/ghalint/blob/3a0bb48351b36e0caee7aa5a649a10a1a084c712/docs/policies/009.md#how-to-ignore-the-violation).

```yaml
# .ghalint.yml
excludes:
  - policy_name: github_app_should_limit_repositories
    workflow_file_path: .github/workflows/ghalint-test.yml
    job_name: test
    step_id: app-token
  - policy_name: github_app_should_limit_repositories
    action_file_path: .github/actions/ghalint-test/action.yml
    step_id: app-token
```

Both `ghalint run` and `ghalint run-action` are expected to success, but `ghalint run-action` fails.

```
% ghalint --version
ghalint version 0.2.10 (613482225fbdea855ed2a561c7cbd737d7aec7d6)
% ghalint run
# OK
% ghalint run-action .github/actions/ghalint-test/action.yml
ERRO[0000] the step violates policies                    action=actions/create-github-app-token action_file_path=.github/actions/ghalint-test/action.yml error="the input `repositories` is required" policy_name=github_app_should_limit_repositories program=ghalint reference="https://github.com/suzuki-shunsuke/ghalint/blob/main/docs/policies/009.md" step_id=app-token version=0.2.10
FATA[0000] ghalint failed
```
