### ISSUE TITLE
Feature request: Excluding actions by org in `action_ref_should_be_full_length_commit_sha`

### ISSUE THREAD

**Issue by takaram** [suzuki-shunsuke/ghalint#649]
You can exclude an action from checking `action_ref_should_be_full_length_commit_sha`, but I would appreciate if we can exclude all actions from a certain organization.
I want to allow using action refs like `@v1` if the action is provided by a "trusted" organization, such as our own one.

**Comment by suzuki-shunsuke** [comment]
Thank you for your feedback.

How about supporting glob patterns?

- https://github.com/suzuki-shunsuke/ghalint/pull/650

```yaml
excludes:
  - policy_name: action_ref_should_be_full_length_commit_sha
    action_name: suzuki-shunsuke/* # glob pattern
```
