### ISSUE TITLE
Allow unix style file paths as `workflow_file_path` on Windows

### ISSUE THREAD

**Issue by takaram** [suzuki-shunsuke/ghalint#738]
Below config file is valid on Linux, but does not work on Windows.
```yaml
excludes:
  - policy_name: checkout_persist_credentials_should_be_false
    workflow_file_path: .github/workflows/ci.yaml
    job_name: test
```

If I change `.github/workflows/ci.yaml` to `.github\workflows\ci.yaml` then it works as expected.

Since I use ghalint both on GitHub Actions (Ubuntu runner) and on Windows PC, it would be better if `.github/workflows/ci.yaml` works on Windows too.
