### ISSUE TITLE
ghalint shows yaml: unmarshal errors when `timeout-minutes: ${{ expression }}` is used

### ISSUE THREAD

**Issue by guitarrapc** [suzuki-shunsuke/ghalint#804]
## tl;dr;

ghalint report error when using `${{ expression }}` in `timeout-minutes:` section like `timeout-minutes: ${{ 1 }}`.

Error message.

```
ERRO[0000] read a workflow file                          error="parse a workflow file as YAML: yaml: unmarshal errors:\n  line 17: cannot unmarshal !!str `${{ ...` into int"
```

## Reproduce workflow

1. Prepare `.github/workflows/foo.yaml` as follows.

```yaml
name: foo
on:
  push:

jobs:
  job:
    strategy:
      matrix:
        timeout-minutes: [1, 2, 3]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 1
    steps:
      - name: dummy
        run: echo "dummy"
        timeout-minutes: ${{ matrix.timeout-minutes }} # works on GitHub, but ghalint shows error.
```

2. Run ghalint.

```sh
$ ghalint run
ERRO[0000] read a workflow file                          error="parse a workflow file as YAML: yaml: unmarshal errors:\n  line 17: cannot unmarshal !!str `${{ mat...` into int" program=ghalint version=1.2.3 workflow_file_path=".github\\workflows\\foo.yaml"
```

## Expected behavior

Ignore when expression is used, or show policy error.
